### ISSUE TITLE
nf_fnc_civilianSettle.sqf - script non funzionante

### ISSUE THREAD

**Issue by Maffaxxx** [Blackbut/FrameworkA3NF#4]
Ho provato d usare lo script in questione, inserendo la stringa nell'init ma non ho avuto successo. Ho provato a mettere il nome del marker con virgolette, senza virgolette, con getmarkerpos, con poco raggio con tnto raggio con o senza edifici ma niente. 

edit: ho visto che c'è una sezione esclusa da */ ho provato ad includerla ma non è successo niente e non so neanche a che serva

l'errore che mi dà l'RPT è questo:

9:12:05 Error in expression <c_randPos;
_class createUnit [_spawnPos,_group];
[_group,_area,getMarkerPos _mar>
 9:12:05   Error position: <_group];
[_group,_area,getMarkerPos _mar>
 9:12:05   Error Undefined variable in expression: _group
 9:12:05 File C:\Users\Maffa\Documents\Arma 3 - Other Profiles\=]NF[=%20Maffa\missions\losangeles.lingor3\server\nf_fnc_civilianSettle.sqf, line 80
 9:12:05 Error in expression <c_randPos;
_class createUnit [_spawnPos,_group];
[_group,_area,getMarkerPos _mar>
 9:12:05   Error position: <_group];
[_group,_area,getMarkerPos _mar>
 9:12:05   Error Undefined variable in expression: _group
 9:12:05 File C:\Users\Maffa\Documents\Arma 3 - Other Profiles\=]NF[=%20Maffa\missions\losangeles.lingor3\server\nf_fnc_civilianSettle.sqf, line 80
 9:12:05 Error in expression <c_randPos;
_class createUnit [_spawnPos,_group];
[_group,_area,getMarkerPos _mar>
 9:12:05   Error position: <_group];
[_group,_area,getMarkerPos _mar>
 9:12:05   Error Undefined variable in expression: _group
 9:12:05 File C:\Users\Maffa\Documents\Arma 3 - Other Profiles\=]NF[=%20Maffa\missions\losangeles.lingor3\server\nf_fnc_civilianSettle.sqf, line 80
 9:12:05 Error in expression <center = _this select 2;

_civ = leader _group;
_group setFormDir round(random 3>
 9:12:05   Error position: <_group;
_group setFormDir round(random 3>
 9:12:05   Error Undefined variable in expression: _group
 9:12:05 File C:\Users\Maffa\Documents\Arma 3 - Other Profiles\=]NF[=%20Maffa\missions\losangeles.lingor3\server\nf_fnc_civilianSettle.sqf, line 30
 9:12:05 Error in expression <center = _this select 2;

_civ = leader _group;
_group setFormDir round(random 3>
 9:12:05   Error position: <_group;
_group setFormDir round(random 3>
 9:12:05   Error Undefined variable in expression: _group
 9:12:05 File C:\Users\Maffa\Documents\Arma 3 - Other Profiles\=]NF[=%20Maffa\missions\losangeles.lingor3\server\nf_fnc_civilianSettle.sqf, line 30
 9:12:05 Error in expression <center = _this select 2;

_civ = leader _group;
_group setFormDir round(random 3>
 9:12:05   Error position: <_group;
_group setFormDir round(random 3>
 9:12:05   Error Undefined variable in expression: _group
 9:12:05 File C:\Users\Maffa\Documents\Arma 3 - Other Profiles\=]NF[=%20Maffa\missions\losangeles.lingor3\server\nf_fnc_civilianSettle.sqf, line 30
 9:12:07 Error in expression < 360);

sleep (random 10);
while {alive _civ} do {
if (behaviour _civ in ["AWARE>
 9:12:07   Error position: <_civ} do {
if (behaviour _civ in ["AWARE>
 9:12:07   Error Undefined variable in expression: _civ
 9:12:07 File C:\Users\Maffa\Documents\Arma 3 - Other Profiles\=]NF[=%20Maffa\missions\losangeles.lingor3\server\nf_fnc_civilianSettle.sqf, line 34
 9:12:11 Error in expression < 360);

sleep (random 10);
while {alive _civ} do {
if (behaviour _civ in ["AWARE>
 9:12:11   Error position: <_civ} do {
if (behaviour _civ in ["AWARE>
 9:12:11   Error Undefined variable in expression: _civ
 9:12:11 File C:\Users\Maffa\Documents\Arma 3 - Other Profiles\=]NF[=%20Maffa\missions\losangeles.lingor3\server\nf_fnc_civilianSettle.sqf, line 34
 9:12:12 Error in expression < 360);

sleep (random 10);
while {alive _civ} do {
if (behaviour _civ in ["AWARE>
 9:12:12   Error position: <_civ} do {
if (behaviour _civ in ["AWARE>
 9:12:12   Error Undefined variable in expression: _civ
 9:12:12 File C:\Users\Maffa\Documents\Arma 3 - Other Profiles\=]NF[=%20Maffa\missions\losangeles.lingor3\server\nf_fnc_civilianSettle.sqf, line 34
 9:12:17 Error in expression <};
};
sleep 0.5;
};
sleep 10;

hideBody _civ;
sleep 5;
deleteVehicle _civ;
};

_>
 9:12:17   Error position: <_civ;
sleep 5;
deleteVehicle _civ;
};

_>
 9:12:17   Error Undefined variable in expression: _civ
 9:12:17 File C:\Users\Maffa\Documents\Arma 3 - Other Profiles\=]NF[=%20Maffa\missions\losangeles.lingor3\server\nf_fnc_civilianSettle.sqf, line 61
 9:12:22 Error in expression <};
};
sleep 0.5;
};
sleep 10;

hideBody _civ;
sleep 5;
deleteVehicle _civ;
};

_>
 9:12:22   Error position: <_civ;
sleep 5;
deleteVehicle _civ;
};

_>
 9:12:22   Error Undefined variable in expression: _civ
 9:12:22 File C:\Users\Maffa\Documents\Arma 3 - Other Profiles\=]NF[=%20Maffa\missions\losangeles.lingor3\server\nf_fnc_civilianSettle.sqf, line 61
 9:12:22 Error in expression <

hideBody _civ;
sleep 5;
deleteVehicle _civ;
};

_civArray = [
"C_man_polo_1_F_>
 9:12:22   Error position: <_civ;
};

_civArray = [
"C_man_polo_1_F_>
 9:12:22   Error Undefined variable in expression: _civ
 9:12:22 File C:\Users\Maffa\Documents\Arma 3 - Other Profiles\=]NF[=%20Maffa\missions\losangeles.lingor3\server\nf_fnc_civilianSettle.sqf, line 63
 9:12:23 Error in expression <};
};
sleep 0.5;
};
sleep 10;

hideBody _civ;
sleep 5;
deleteVehicle _civ;
};

_>
 9:12:23   Error position: <_civ;
sleep 5;
deleteVehicle _civ;
};

_>
 9:12:23   Error Undefined variable in expression: _civ
 9:12:23 File C:\Users\Maffa\Documents\Arma 3 - Other Profiles\=]NF[=%20Maffa\missions\losangeles.lingor3\server\nf_fnc_civilianSettle.sqf, line 61
 9:12:27 Error in expression <

hideBody _civ;
sleep 5;
deleteVehicle _civ;
};

_civArray = [
"C_man_polo_1_F_>
 9:12:27   Error position: <_civ;
};

_civArray = [
"C_man_polo_1_F_>
 9:12:27   Error Undefined variable in expression: _civ
 9:12:27 File C:\Users\Maffa\Documents\Arma 3 - Other Profiles\=]NF[=%20Maffa\missions\losangeles.lingor3\server\nf_fnc_civilianSettle.sqf, line 63
 9:12:28 Error in expression <

hideBody _civ;
sleep 5;
deleteVehicle _civ;
};

_civArray = [
"C_man_polo_1_F_>
 9:12:28   Error position: <_civ;
};

_civArray = [
"C_man_polo_1_F_>
 9:12:28   Error Undefined variable in expression: _civ
 9:12:28 File C:\Users\Maffa\Documents\Arma 3 - Other Profiles\=]NF[=%20Maffa\missions\losangeles.lingor3\server\nf_fnc_civilianSettle.sqf, line 63

**Comment by Blackbut** [comment]
Grazie di aver segnalato la disgrazia, il problema è stato risolto.
